name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: 'Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'fix'
      - 'bug'
      - 'chore'
  default: patch
template: |
  ## What's Changed
  $CHANGES

autolabeler:
  - label: 'bug'
    regex:
      - '/^fix/i'
      - '/^bug/i'
  - label: 'feature'
    regex:
      - '/^feat/i'
      - '/^feature/i'
  - label: 'chore'
    regex:
      - '/^chore/i'